import type { Metadata } from 'next';
import Nav from './nav';

export const metadata: Metadata = {
  title: 'C⨀ZEN | PANEL',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <Nav />
      {children}
    </main>
  );
}
