import type { Metadata } from 'next';
import Nav from './nav';
import CozenLogo from '@/app/assets/icon/cozen-logo';
import { ModeToggle } from '@/components/mode-toggle';

export const metadata: Metadata = {
  title: 'C⨀ZEN | PANEL',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <header className="flex items-center justify-between">
        <CozenLogo />
        <ModeToggle />
      </header>
      <main>
        <Nav />

        {children}
      </main>
    </>
  );
}
