import type { Metadata } from 'next';

import CozenLogo from '../assets/icon/cozen-logo';
// import { Ravi } from '../assets/font';

import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';

export const metadata: Metadata = {
  title: 'C⨀ZEN | PANEL',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main
      className={cn(
        'mx-auto flex h-full flex-col gap-3 p-3 xs:gap-6 xs:p-6 sm:gap-9 sm:p-9'
      )}>
      <header className="flex items-center justify-between">
        <CozenLogo />

        <Button size="icon" variant="outline">
          B
        </Button>
      </header>

      {children}
    </main>
  );
}
