import type { Metadata } from 'next';

import { cn } from '@/lib/utils';
import './globals.css';
import { Satoshi } from './assets/font';

import { ThemeProvider } from '@/components/theme-provider';
import NewsMarquee from '@/components/news-marquee';

export const metadata: Metadata = {
  title: 'C⨀ZEN',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn('layout-height mx-auto antialiased', Satoshi.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <NewsMarquee />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
