import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'C⨀ZEN | DASHBOARD',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main className="mx-auto w-full max-w-lg">{children}</main>;
}
